### ISSUE TITLE
Issue with Refunds & Tracking ID's Program

### ISSUE THREAD

**Issue by tanuja-blumaple** [daintree2016/Tools-related-Issues#10]
@daintree2016/it-services 
Hi Team,
We are unable to run the refunds and tracking ID program. The refund program is getting closed after the credentials are given. The tracking ID program is showing the below error. Please check and update.

Thanks
Tanuja
![Screenshot 2024-10-05 145802](https://github.com/user-attachments/assets/62ed48bb-f3d8-48ec-8656-8c3edc10cbed)

**Comment by raj7032** [comment]
Hi Tanuja,
Thanks for reaching out, looks like the issue is due to the expired credentials of blumaple API. Here I have fixed the issue now and updated the link, our team member will contact you shortly for guidance.
--Rajkumar

**Comment by tanuja-blumaple** [comment]
Hi Raj Kumar,
We tried to run the refund program through the updated link that Navya shared but we are still facing the same issue. Please check and update.

Thanks
Tanuja

**Comment by raj7032** [comment]
ok I have checked the script and yeah found some issue there, so hope it
got fixed now.
use the same link to download and run it to check the results.

**Comment by tanuja-blumaple** [comment]
Hi Rajkumar,
The issue is fixed now and we have no challenges now in running the program. Thank you for your help in this.

Thanks
Tanuja
